# Generated by Django 6.0 on 2025-12-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flight_search_app",
            "0002_alter_paymentattempt_id_alter_usercontact_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentattempt",
            name="card_number",
            field=models.CharField(default="0000000000000000", max_length=16),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="cvv",
            field=models.CharField(default="000", max_length=4),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="passport_number",
            field=models.CharField(default="UNKNOWN", max_length=20),
        ),
    ]
