# Generated by Django 6.0 on 2025-12-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flight_search_app",
            "0003_paymentattempt_card_number_paymentattempt_cvv_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iata_code",
                    models.CharField(db_index=True, max_length=3, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("popularity", models.IntegerField(default=0)),
            ],
        ),
    ]
